### ISSUE TITLE
no query results for  custom class names due to cache

### ISSUE THREAD

**Issue by rajdeepv** [calabash/calabash-android-server#31]
In my app, I have a facebook login dialog with class "com.facebook.internal.WebDialog$3"
In one case I poll for this dialog to appear and it never succeeds even if it appears on UI.
Reason:
1) Initially "com.facebook.internal.WebDialog$3" is NOT present and I do `query("com.facebook.internal.WebDialog$3")`
2) This results in `[]` result and at the same time:
     `executeQuery()` method optimize the query. However, at this point, `qualifiedClassName` of optimised query is detected as `null` and it gets cached
3) Now, when dialog appears on screen and I do a `query("com.facebook.internal.WebDialog$3") ` again, it should return results BUT, it returns `[].`
     This is because: `optimizedQuery` is not null and at the same time it has qualifiedClassName = null in cache from previous step.

to solve this, I have modified the executeQuery() method as below  

	public QueryResult executeQuery() {
        List<UIQueryAST> queryPath = parseQuery(this.queryString);
		List<UIQueryAST> optimizedQuery = QueryOptimizationCache.getCacheFor(this.queryString);

		boolean needOptimization = false;
		if (optimizedQuery != null) {
			for (int i = 0; i < optimizedQuery.size(); i++) {
				UIQueryAST step = optimizedQuery.get(i);
				if (step instanceof UIQueryASTClassName) {
					if (((UIQueryASTClassName) step).qualifiedClassName == null) {
						needOptimization = true;
					}
				}
			}
		}

		if (needOptimization || optimizedQuery == null) {
			QueryOptimizer queryOptimizer = new GeneralUIQueryOptimizer();
			optimizedQuery = queryOptimizer.optimize(queryPath);
			QueryOptimizationCache.cache(this.queryString, optimizedQuery);
		}

				return UIQueryEvaluator.evaluateQueryWithOptions(optimizedQuery, rootViews(),
						parseOperations(this.operations));
	}

**Comment by TobiasRoikjer** [comment]
Thank you! https://github.com/calabash/calabash-android-server/pull/33

**Comment by rajdeepv** [comment]
Thanks @TobiasRoikjer
