### ISSUE TITLE
Why I have no calabash-android-server after I install calabash-android

### ISSUE THREAD

**Issue by jwtang** [calabash/calabash-android-server#41]
I have install calabash-android, and it will install instrumentation-backend when I run calabash-android. But I found I have no calabash-android-server in my Mac. Do I need to install and configure it? And how to install it?

**Comment by TobiasRoikjer** [comment]
The calabash-android-server is the source code for the calabash android server. The Calabash-android ruby gem ships with a compiled version of this server.

You do not need to clone or download anything from the repo in order to run Calabash-android.
