### ISSUE TITLE
Can I specify the path to the step_definitions file

### ISSUE THREAD

**Issue by jwtang** [calabash/calabash-android-server#42]
I don't want to put the step_definitions file in the step_definitions folder, I created a lib folder to put step_definitions files, can I specify a step_definitions file path for the feature file?

**Comment by TobiasRoikjer** [comment]
This is a Cucumber-structure question. Calabash is just run by Cucumber, and we put no special requirements on the structure.

By default Cucumber loads everything inside the features directory (recursively). You may be able to add another path by specifying it in the cucumber ENV file, but I would not recommend that.

Personally, I save my step definitions in a directory inside features/steps :)
