### ISSUE TITLE
Broken Touch and query visibility

### ISSUE THREAD

**Issue by rajdeepv** [calabash/calabash-android-server#78]
**Background**
We have around 1400 tests running stable on Calabash 0.9.2 with Oreo emulators. I tried to update to 0.9.6 and about 30 different tests always fail due to below reasons:
1. The query sometimes returns blank results
2. Touch was successful but a completely wrong point on screen was touched than desired

**I observed that:**

- `query("* id:'btn'")`  yields empty results but `query("all * id:'btn'")` returns desired result which has `visible => false` even though element is visible. This can be easily reproduced by repeating query in a loop
- On enabling pointer location in developer options (`adb shell settings put system pointer_location 1`), I saw wrong point was touched once in 10 attempts

On further debugging on server side, I found the casue was change in `getViewLocationOnScreen(View view)` in `UIQueryUtils` class. This is used for visibility as well as for touch gestures

**If I change this method back to what it was as below, everythig works fine:**
```
	public static int[] getViewLocationOnScreen(View view) {
		ViewWrapper viewWrapper = new ViewWrapper(view);

		return viewWrapper.getLocationOnScreen();
	}

```

**This is the change from 3a91292f9974b92cba282f0775acd012bd7fe548**

```
        public static int[] getViewLocationOnScreen(View view) {
-               ViewWrapper viewWrapper = new ViewWrapper(view);
+               if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.ICE_CREAM_SANDWICH_MR1
+                               && Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP_MR1) {
+                       ViewWrapper viewWrapper = new ViewWrapper(view);

-               return viewWrapper.getLocationOnScreen();
+                       return viewWrapper.getLocationOnScreen();
+               }
+
+               int[] location = new int[2];
+               view.getLocationOnScreen(location);
+
+               return location;
        }
```

**Comment by AndreyMitsyk** [comment]
@jmoody Google fixed many view wrappers issues on api 22. Maybe an official fixes is not stable for us. We can't use custom (old) `ViewWrapper` on latest android due to deprecation, but we can enable it on Android < 28 if necessary.

**Comment by rajdeepv** [comment]
Thanks @AndreyMitsyk 
I can confirm that after removing branching, tests are stable again.  Maybe it's a good idea to enable it on Android < 28 for now. I will test what happens on Android 'P' once I get required emulators in our CI.
